### ISSUE TITLE
XmlMind og CSS-stilark

### ISSUE THREAD

**Issue by unhammer** [giellalt/dict-sme-nob#2]
@snomos  @Trondtr 

xmlmind gjenkjenner ikkje 
`<?xml-stylesheet alternate="yes" title="Hierarchical view" media="screen,tv,projection" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css" type="text/css"?>
`
pga. `media="screen,tv,projection"` er inni der. Viss eg fjernar det attributtet, så dukkar stilarka opp i View-menyen, men med varsel. Viss eg endrar til _XXE-varianten av css-fila så forsvinn òg varsel og ting fungerer:

![image](https://github.com/giellalt/dict-sme-nob/assets/56868/1679290f-67a8-41ab-b76b-d42616bbe59c)

Eg ser frå http://www.xmlmind.com/pipermail/xmleditor-support/2010-March/008394.html at det var snakk om ein workaround for å unngå varsel – var det tanken at dei som bruker XmlMind sjølv skulle konfigurera programmet til å bruka dei xxe-spesifikke stilarka? 

Hadde det kanskje vore mogleg å i staden ha begge inni der, a la 

```
diff --git a/src/Adv_smenob.xml b/src/Adv_smenob.xml
index cd7c414..cbe70a4 100644
--- a/src/Adv_smenob.xml
+++ b/src/Adv_smenob.xml
@@ -1,5 +1,7 @@
+<?xml-stylesheet title="Dictionary view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css" type="text/css"?>
+<?xml-stylesheet alternate="yes" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css"?>
 <?xml-stylesheet title="Dictionary view" media="screen,tv,projection" href="../../giella-core/dicts/scripts/gt_dictionary.css" type="text/css"?>
 <?xml-stylesheet alternate="yes" title="Hierarchical view" media="screen,tv,projection" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css" type="text/css"?>
 <!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../../giella-core/dicts/scripts/gt_dictionary.dtd">
 <r xmlns:xhtml="http://www.w3.org/1999/xhtml" id="smenob" xml:lang="sme">
   <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve">
```

Då vil iallfall XmlMind finna berre XXE-variantane (utan at brukaren av XmlMind må konfigurera noko i innstillingar), men eg veit ikkje om dette vil ha andre negative effektar (i utgangspunktet er jo CSS Cascading, så viss XXE.css blir importert to gongar så bør det teoretisk vera som om det blei importert éin gong; ev. går det an å fjerna XXE-importen frå gt_dictionary.css og anta at importen alltid skjer først i xml-filene).

**Comment by snomos** [comment]
Eg ser ingen grunn til at det ikkje skulle gå, det høyrest ut som ei fornuftig endring.

**Comment by unhammer** [comment]
Er nokon av desse filene generert eller automatisk endra eller oppdatert, eller kan eg berre gjera eit stort `sed`-kall for å endra alt?

**Comment by snomos** [comment]
Eg meiner dei fleste om ikkje alle er laga manuelt, så eit stort `sed`-kall burde vera tingen å gjera

**Comment by unhammer** [comment]
mogleg det bør gjerast i andre dict-mapper òg, https://github.com/giellalt/dict-sme-nob/commit/0fdd10fd024509f9d22560733cf5cb169ccfa8e3 har skriptet eg køyrte

**Comment by unhammer** [comment]
Jf. http://www.xmlmind.com/pipermail/xmleditor-support/2024-June/012935.html så aksepterer xmlmind per i dag både

```
<?xml-stylesheet                title="Dictionary view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css" type="text/css" ?>
```
og
```
<?xml-stylesheet media="screen" title="Dictionary view" href="../../giella-core/dicts/scripts/gt_dictionary.css" type="text/css"?>
```
(visstnok òg "xmlmind-xml-editor", men det fekk eg ikkje til å fungera)

og dei vil sannsynlegvis i ei framtidig utgåve akseptera `media="screen,tv,projection"` pga. `screen` er ein del av det.

Er det slik at `screen` blir brukt andre stader som skal ha ulik CSS?

(Kan me bruka `print` heller til den andre CSS-en?)

**Comment by Trondtr** [comment]
Ja, det bør bli gjort i alle dict-mapper. Så er spørsmålet om alle ordbøker bør ha same dtd eller ikkje. Det ser ut til at vi ikkje har sterk nok rygg til å bere byrda av mange dtd-filer, så det talar for at det (i alle fall som default) skal vere slik at vi viser til same dtd-fil.

Dei ordbøkene som er under aktiv utvikling (-sme-, -sma-, -sms-, -smn-, -fkv-, -fit-, eigentleg også potensielt -mns-) bør i alle fall få den nye vidundermedisinen, eigentleg vel alle når ein er i gang med prosessen.

**Comment by unhammer** [comment]
Det eg er litt bekymra for med løysinga eg sjekka inn her er at ei seinare utgåve av XmlMind lærer seg å lesa komma-separerte verdiar av `@media`, og finn ut at den skal lasta inn både `gt_dictionary_XXE.css` (utan `@media`-attributt) og `gt_dictionary.css` (med `@media="screen,tv,…"`) – der den siste vil gi masse feilmeldingar. 

Så *viss* ev. andre brukarar av `@media=screen` ikkje treng meir CSS enn det som er i XXE.css, så hadde det unngått problem i framtida å heller bruka
- `<?xml-stylesheet media="screen" href="gt_dictionary_XXE.css" …`
- `<?xml-stylesheet media="print,tv,projection" href="gt_dictionary.css" …`

**Comment by snomos** [comment]
Det høyrest fornuftig ut, gjer det slik @unhammer

**Comment by unhammer** [comment]
:heavy_check_mark:
